export const LEVELS = [
  {
    "id_nivel": "mision_01",
    "title": "Hola, Python",
    "dificultad": "Básico",
    "modalidad": "Terminal",
    "briefing_mision": "Tu aventura en Python arranca con un saludo. Es hora de demostrar que el intérprete te obedece: haz que muestre por consola el mensaje más famoso de la programación.",
    "init_code": "# Escribe tu primera línea de código Python\n",
    "solution_code": "print(\"Hola, mundo\")\n",
    "expected_output": "Hola, mundo",
    "conceptos": ["La función print() muestra texto por consola.", "El texto va entre comillas.", "Python ejecuta el código de arriba hacia abajo."],
    "pistas": ["Busca en la Enciclopedia Python la ficha de print().", "El texto exacto del saludo está entre paréntesis."],
    "keywords": ["print"]
  },
  {
    "id_nivel": "mision_02",
    "title": "Variables y Detective",
    "dificultad": "Básico",
    "modalidad": "Depuración",
    "briefing_mision": "Un recluta novato dejó su código medio roto: mezcló variables y cometió un error al imprimir. Encuentra el fallo y haz que el programa muestre el nombre y la edad correctos.",
    "init_code": "",
    "query_defectuoso": "nombre = \"Ada\"\nprint(nombre)\nedad = 36\nprint(edda)\n",
    "solution_code": "nombre = \"Ada\"\nprint(nombre)\nedad = 36\nprint(edad)\n",
    "expected_output": "Ada\n36",
    "explicacion": "El error estaba en print(edda): la variable se llama edad, no edda. Python distingue mayúsculas y minúsculas, así que los nombres deben ser exactos.",
    "conceptos": ["Las variables guardan valores.", "El nombre de una variable debe ser exacto al usarla.", "print() muestra el valor de una variable."],
    "pistas": ["Ejecuta el código y lee el error: el nombre del problema aparece al final.", "La variable que se imprime se llama igual que 'edad'."],
    "keywords": ["print", "nombre", "edad"]
  },
  {
    "id_nivel": "mision_03",
    "title": "Matemáticas del Cuartel",
    "dificultad": "Básico",
    "modalidad": "Terminal",
    "briefing_mision": "El cuartel necesita calcular cuentas con dos códigos de serie. Muestra el resultado de las seis operaciones aritméticas básicas entre dos números: suma, resta, multiplicación, división, división entera y módulo.",
    "init_code": "a = 10\nb = 3\n# Escribe las operaciones\n",
    "solution_code": "a = 10\nb = 3\nprint(a + b)\nprint(a - b)\nprint(a * b)\nprint(a / b)\nprint(a // b)\nprint(a % b)\n",
    "expected_output": "13\n7\n30\n3.3333333333333335\n3\n1",
    "conceptos": ["+ suma, - resta, * multiplica.", "/ divide con decimales.", "// división entera y % módulo (resto)."],
    "pistas": ["Usa los operadores sobre a y b.", "La división normal (/) da decimales, // da entero y % da el resto."],
    "keywords": ["print", "a", "b"]
  },
  {
    "id_nivel": "mision_04",
    "title": "Operador Especial",
    "dificultad": "Básico",
    "modalidad": "Terminal",
    "briefing_mision": "Los agentes tienen nombre y código de identificación. Usa el formato que inserta variables dentro de texto para construir el mensaje de presentación.",
    "init_code": "nombre = \"Ada\"\npuntaje = 95\n# Construye el mensaje\n",
    "solution_code": "nombre = \"Ada\"\npuntaje = 95\nprint(f\"Hola {nombre}, tu puntaje es {puntaje}\")\n",
    "expected_output": "Hola Ada, tu puntaje es 95",
    "conceptos": ["Las f-strings insertan variables dentro del texto.", "Se escriben con una f delante y {variable} dentro."],
    "pistas": ["La letra f va justo antes de las comillas de apertura.", "Cada variable que quieras insertar va entre llaves {}."],
    "keywords": ["print", "nombre", "puntaje"]
  },
  {
    "id_nivel": "mision_05",
    "title": "Verdad o Falso",
    "dificultad": "Básico",
    "modalidad": "Terminal",
    "briefing_mision": "Una sonda robótica evalúa condiciones de seguridad. Muestra el resultado (True o False) de las cinco comparaciones y combinaciones lógicas entre los valores indicados.",
    "init_code": "a = 7\n# Evalúa las condiciones\n",
    "solution_code": "a = 7\nprint(a > 5)\nprint(a == 7)\nprint(a != 8)\nprint(a >= 10 and a < 20)\nprint(a > 10 or a == 7)\n",
    "expected_output": "True\nTrue\nTrue\nFalse\nTrue",
    "conceptos": ["> , < , == , != comparan valores.", "and exige que las dos condiciones sean verdaderas.", "or basta con que una sea verdadera."],
    "pistas": ["== compara igualdad; != compara diferencia.", "and True si ambas; or True si al menos una."],
    "keywords": ["print", "a"]
  },
  {
    "id_nivel": "mision_06",
    "title": "Transformación de Datos",
    "dificultad": "Básico",
    "modalidad": "Terminal",
    "briefing_mision": "Los datos llegan como texto y el sistema necesita números. Convierte los valores según corresponda y muestra los tres resultados de la misión.",
    "init_code": "numero_texto = \"250\"\nprecio = \"19.99\"\n# Convierte y opera\n",
    "solution_code": "numero_texto = \"250\"\ncantidad = int(numero_texto)\nprint(cantidad * 2)\nprecio = float(\"19.99\")\nprint(precio + 0.01)\nprint(\"Nivel \" + str(3))\n",
    "expected_output": "500\n20.0\nNivel 3",
    "conceptos": ["int() convierte texto a entero.", "float() convierte a número con decimales.", "str() convierte a texto para poder unirlo."],
    "pistas": ["int(\"250\") da el número 250.", "Para sumar 0.01 al precio necesitas float.", "str(3) es el texto \"3\"."],
    "keywords": ["print", "int", "float", "str"]
  },
  {
    "id_nivel": "mision_07",
    "title": "Jefe de Escuadrón",
    "dificultad": "Intermedio",
    "modalidad": "Terminal",
    "briefing_mision": "Un sistema califica a los reclutas según su puntuación. Escribe la lógica de decisión que asigne la calificación correcta según los rangos dados y la muestre.",
    "init_code": "puntuacion = 85\n# Escribe la lógica de decisión\n",
    "solution_code": "puntuacion = 85\nif puntuacion >= 90:\n    calificacion = \"A\"\nelif puntuacion >= 80:\n    calificacion = \"B\"\nelif puntuacion >= 70:\n    calificacion = \"C\"\nelse:\n    calificacion = \"D\"\nprint(f\"Calificación: {calificacion}\")\n",
    "expected_output": "Calificación: B",
    "conceptos": ["if ejecuta un bloque si su condición es verdadera.", "elif añade más condiciones en cascada.", "else captura cualquier otro caso."],
    "pistas": ["El rango >= 80 y < 90 corresponde a la letra B.", "Los bloques se indentan con 4 espacios."],
    "keywords": ["if", "elif", "else", "print", "puntuacion"]
  },
  {
    "id_nivel": "mision_08",
    "title": "Licencia de Conducción",
    "dificultad": "Intermedio",
    "modalidad": "Depuración",
    "briefing_mision": "El registro civil tiene un fallo: un candidato que cumple todos los requisitos aparece rechazado. Corrige la condición para que el veredicto sea correcto.",
    "init_code": "",
    "query_defectuoso": "edad = 20\ntiene_licencia = True\nif edad >= 18 and tiene_licencia == \"True\":\n    print(\"Puedes conducir\")\nelse:\n    print(\"No puedes conducir\")\n",
    "solution_code": "edad = 20\ntiene_licencia = True\nif edad >= 18 and tiene_licencia:\n    print(\"Puedes conducir\")\nelse:\n    print(\"No puedes conducir\")\n",
    "expected_output": "Puedes conducir",
    "explicacion": "tiene_licencia es True (booleano), pero se comparaba con el texto \"True\". Comparar un booleano con un string siempre da False, por eso salía el veredicto equivocado.",
    "conceptos": ["and combina condiciones.", "Comparar un booleano contra un string \"True\" es un error clásico.", "Los bloques if/else se indentan con 4 espacios."],
    "pistas": ["Ejecuta el código y mira qué imprime.", "La variable tiene_licencia ya es True, no hace falta compararla con un texto."],
    "keywords": ["if", "else", "and", "print"]
  },
  {
    "id_nivel": "mision_09",
    "title": "Suma Repetitiva",
    "dificultad": "Intermedio",
    "modalidad": "Terminal",
    "briefing_mision": "El cuartel suma intensidades de señal del 1 al 10. Escribe el bucle que recorra esos valores y acumule la suma, y muestra el total final.",
    "init_code": "total = 0\n# Escribe el bucle\n",
    "solution_code": "total = 0\nfor i in range(1, 11):\n    total = total + i\nprint(f\"Suma del 1 al 10: {total}\")\n",
    "expected_output": "Suma del 1 al 10: 55",
    "conceptos": ["for itera sobre range(inicio, fin).", "range(1, 11) no incluye el 11.", "Un acumulador suma dentro del bucle."],
    "pistas": ["range(1, 11) genera 1,2,...,10.", "Dentro del bucle: total = total + i."],
    "keywords": ["for", "range", "print", "total"]
  },
  {
    "id_nivel": "mision_10",
    "title": "Cuenta Regresiva",
    "dificultad": "Intermedio",
    "modalidad": "Depuración",
    "briefing_mision": "La torre de lanzamiento informa pero se salta números. El bucle termina antes de tiempo. Corrige la condición del while para que la cuenta llegue a 1.",
    "init_code": "",
    "query_defectuoso": "contador = 3\nwhile contador >= 2:\n    print(f\"Cuenta regresiva: {contador}\")\n    contador = contador - 1\nprint(\"Despegue!\")\n",
    "solution_code": "contador = 3\nwhile contador > 0:\n    print(f\"Cuenta regresiva: {contador}\")\n    contador = contador - 1\nprint(\"Despegue!\")\n",
    "expected_output": "Cuenta regresiva: 3\nCuenta regresiva: 2\nCuenta regresiva: 1\nDespegue!",
    "explicacion": "La condición >= 2 hace que el bucle se detenga al llegar a 2. Con > 0 el bucle continúa mientras queden números, imprimiendo también el 1.",
    "conceptos": ["while repite mientras su condición sea verdadera.", "El cuerpo debe reducir la variable de control.", "Cuidado con los límites: >= 2 deja fuera el 1."],
    "pistas": ["Cuenta qué números imprime con la condición actual.", "Para imprimir el 1, el bucle debe seguir mientras contador sea mayor que 0."],
    "keywords": ["while", "print", "contador"]
  },
  {
    "id_nivel": "mision_11",
    "title": "Escape de Bucle",
    "dificultad": "Intermedio",
    "modalidad": "Auditoría",
    "briefing_mision": "El radar debe saltarse el valor 3 y seguir mostrando los demás. Algo interrumpe el escaneo por completo. Ubica la instrucción que provoca el fallo.",
    "init_code": "",
    "audit_tokens": [
      "for i in range(1, 6):",
      "    if i == 3:",
      "        break",
      "    print(i)"
    ],
    "token_error_index": 2,
    "solution_code": "for i in range(1, 6):\n    if i == 3:\n        continue\n    print(i)\n",
    "expected_output": "1\n2\n4\n5",
    "explicacion": "break termina el bucle entero, por eso solo se mostraban 1 y 2. La instrucción correcta es continue, que salta a la siguiente iteración y sigue mostrando 4 y 5.",
    "conceptos": ["break detiene el bucle.", "continue salta a la siguiente iteración."],
    "pistas": ["Fíjate en qué línea interrumpe el bucle.", "Se quiere saltar SOLO el 3, no detener todo."],
    "keywords": ["for", "range", "break", "continue"]
  },
  {
    "id_nivel": "mision_12",
    "title": "El Escondite Indexado",
    "dificultad": "Intermedio",
    "modalidad": "Terminal",
    "briefing_mision": "Un archivo de colores está cifrado por posición. Recupera el primer, el tercero y el último elemento, modifica el segundo y muestra la lista final.",
    "init_code": "colores = [\"rojo\", \"verde\", \"azul\", \"amarillo\"]\n# Recupera e imprime\n",
    "solution_code": "colores = [\"rojo\", \"verde\", \"azul\", \"amarillo\"]\nprint(colores[0])\nprint(colores[2])\nprint(colores[-1])\ncolores[1] = \"naranja\"\nprint(colores)\n",
    "expected_output": "rojo\nazul\namarillo\n['rojo', 'naranja', 'azul', 'amarillo']",
    "conceptos": ["Las listas se indexan desde 0.", "colores[-1] es el último elemento.", "Las listas son modificables: colores[1] = valor."],
    "pistas": ["El primer elemento está en la posición 0.", "El índice negativo cuenta desde el final."],
    "keywords": ["print", "colores"]
  },
  {
    "id_nivel": "mision_13",
    "title": "Orden de Batalla",
    "dificultad": "Intermedio",
    "modalidad": "Terminal",
    "briefing_mision": "Una lista de códigos llega desordenada y con un elemento extra. Añade el código que falta, ordénala, muestra su tamaño y luego inviértela.",
    "init_code": "numeros = [4, 1, 3]\n# Ordena y completa\n",
    "solution_code": "numeros = [4, 1, 3]\nnumeros.append(2)\nnumeros.sort()\nprint(numeros)\nprint(len(numeros))\nnumeros.reverse()\nprint(numeros)\n",
    "expected_output": "[1, 2, 3, 4]\n4\n[4, 3, 2, 1]",
    "conceptos": ["append() añade al final.", "sort() ordena la lista en su lugar.", "len() da la cantidad de elementos."],
    "pistas": ["Falta el 2: añádelo con append.", "sort() ordena de menor a mayor."],
    "keywords": ["append", "sort", "len", "reverse", "print"]
  },
  {
    "id_nivel": "mision_14",
    "title": "Coordenadas Fijas",
    "dificultad": "Intermedio",
    "modalidad": "Depuración",
    "briefing_mision": "El GPS intenta modificar unas coordenadas que no aceptan cambios. Cambia la estructura para que el sistema permita actualizar el valor sin errores.",
    "init_code": "",
    "query_defectuoso": "punto = (10, 20)\npunto[1] = 30\nprint(f\"x={punto[0]}, y={punto[1]}\")\n",
    "solution_code": "punto = [10, 20]\npunto[1] = 30\nprint(f\"x={punto[0]}, y={punto[1]}\")\n",
    "expected_output": "x=10, y=30",
    "explicacion": "Las tuplas son inmutables y no permiten asignar índices. Al cambiar la tupla por una lista se puede modificar la posición 1.",
    "conceptos": ["Las tuplas no se pueden modificar (inmutables).", "Las listas sí permiten cambiar elementos.", "El mensaje de error TypeError lo delata."],
    "pistas": ["Ejecuta y lee el error: dice 'tuple' object does not support item assignment.", "La solución es usar una estructura mutable con la misma sintaxis."],
    "keywords": ["tuple", "list", "print"]
  },
  {
    "id_nivel": "mision_15",
    "title": "Agenda Secreta",
    "dificultad": "Intermedio",
    "modalidad": "Terminal",
    "briefing_mision": "La central tiene una agenda de contactos. Consulta el teléfono de un agente, añade un nuevo contacto, muestra la lista de nombres ordenada, el total de contactos y qué pasa al buscar a un agente inexistente.",
    "init_code": "agenda = {\"Ana\": \"555-1000\", \"Luis\": \"555-2000\"}\n# Consulta y actualiza\n",
    "solution_code": "agenda = {\"Ana\": \"555-1000\", \"Luis\": \"555-2000\"}\nagenda[\"Marta\"] = \"555-3000\"\nprint(agenda[\"Ana\"])\nprint(sorted(agenda))\nprint(len(agenda))\nprint(agenda.get(\"Pedro\", \"No está\"))\n",
    "expected_output": "555-1000\n['Ana', 'Luis', 'Marta']\n3\nNo está",
    "conceptos": ["Los dicts guardan pares clave: valor.", "agenda[\"clave\"] lee o añade valores.", "get(clave, default) devuelve un valor si falta."],
    "pistas": ["sorted(agenda) ordena las claves.", "Usa get con un segundo argumento para el caso inexistente."],
    "keywords": ["sorted", "len", "get", "print"]
  },
  {
    "id_nivel": "mision_16",
    "title": "Filtro de Datos",
    "dificultad": "Intermedio",
    "modalidad": "Terminal",
    "briefing_mision": "El escáner genera una lista de números. Crea una lista con los pares y otra con los cuadrados usando el estilo compacto de construcción de listas.",
    "init_code": "numeros = [1, 2, 3, 4, 5, 6]\n# Crea las listas nuevas\n",
    "solution_code": "numeros = [1, 2, 3, 4, 5, 6]\npares = [n for n in numeros if n % 2 == 0]\ncuadrados = [n * n for n in numeros]\nprint(pares)\nprint(cuadrados)\n",
    "expected_output": "[2, 4, 6]\n[1, 4, 9, 16, 25, 36]",
    "conceptos": ["Comprensión de listas: [expr for x in datos if cond].", "Se puede añadir un filtro con if.", "n % 2 == 0 detecta pares."],
    "pistas": ["La sintaxis va entre corchetes.", "El filtro de pares va al final, con if."],
    "keywords": ["for", "if", "print"]
  },
  {
    "id_nivel": "mision_17",
    "title": "Función del Área",
    "dificultad": "Avanzado",
    "modalidad": "Terminal",
    "briefing_mision": "Construye una función que calcule el área de un rectángulo a partir de su base y su altura. Úsala con dos terrenos distintos y muestra ambos resultados.",
    "init_code": "# Define la función area_rectangulo\n",
    "solution_code": "def area_rectangulo(base, altura):\n    return base * altura\n\nprint(area_rectangulo(5, 4))\nprint(area_rectangulo(7, 2))\n",
    "expected_output": "20\n14",
    "conceptos": ["def define una función.", "Los parámetros reciben los valores al llamarla.", "return devuelve un valor para usar fuera."],
    "pistas": ["La función se llama area_rectangulo y recibe base y altura.", "return base * altura."],
    "keywords": ["def", "return", "print"]
  },
  {
    "id_nivel": "mision_18",
    "title": "Saludo Flexible",
    "dificultad": "Avanzado",
    "modalidad": "Terminal",
    "briefing_mision": "Diseña una función de saludo que funcione con saludo propio y con uno por defecto, y otra que sume cualquier cantidad de números. Demuestra ambas.",
    "init_code": "# Define saludar y suma_total\n",
    "solution_code": "def saludar(nombre, saludo=\"Hola\"):\n    print(f\"{saludo}, {nombre}!\")\n\ndef suma_total(*numeros):\n    return sum(numeros)\n\nsaludar(\"Lena\")\nsaludar(\"Lena\", \"Buenos días\")\nprint(suma_total(1, 2, 3, 4))\n",
    "expected_output": "Hola, Lena!\nBuenos días, Lena!\n10",
    "conceptos": ["Los parámetros por defecto tienen un valor si no se pasa.", "*args agrupa cualquier cantidad de argumentos.", "sum() suma una secuencia."],
    "pistas": ["saludo=\"Hola\" da el valor por defecto.", "def suma_total(*numeros) recoge todos los argumentos en una tupla."],
    "keywords": ["def", "return", "sum", "print"]
  },
  {
    "id_nivel": "mision_19",
    "title": "Cociente y Resto",
    "dificultad": "Avanzado",
    "modalidad": "Ensamblaje",
    "briefing_mision": "Necesitas una función que reparta 17 recursos en grupos de 5 y devuelva dos datos a la vez: cuántos grupos completos se forman y cuántos recursos sobran. Ensambla el bloque que lo consigue.",
    "init_code": "",
    "dnd_blocks": [
      "def dividir(a, b):",
      "    cociente = a // b",
      "    resto = a % b",
      "    return cociente, resto",
      "c, r = dividir(17, 5)",
      "print(f\"Cociente: {c}\")",
      "print(f\"Resto: {r}\")"
    ],
    "solution_code": "def dividir(a, b):\n    cociente = a // b\n    resto = a % b\n    return cociente, resto\nc, r = dividir(17, 5)\nprint(f\"Cociente: {c}\")\nprint(f\"Resto: {r}\")\n",
    "expected_output": "Cociente: 3\nResto: 2",
    "conceptos": ["Una función puede devolver varios valores separados por coma.", "Se desempaquetan al asignarlos: c, r = ...", "// es división entera y % es el resto."],
    "pistas": ["El bloque 'return' devuelve dos valores.", "La línea c, r = dividir(17, 5) captura ambos."],
    "keywords": ["def", "return", "print"]
  },
  {
    "id_nivel": "mision_20",
    "title": "Conversión Protegida",
    "dificultad": "Avanzado",
    "modalidad": "Depuración",
    "briefing_mision": "El sistema intenta convertir un texto a número y se cae porque captura el error equivocado. Corrige la excepción para que el programa responda con elegancia.",
    "init_code": "",
    "query_defectuoso": "num = \"abc\"\ntry:\n    valor = int(num)\n    print(\"Conversión exitosa\")\nexcept TypeError:\n    print(\"No se pudo convertir\")\n",
    "solution_code": "num = \"abc\"\ntry:\n    valor = int(num)\n    print(\"Conversión exitosa\")\nexcept ValueError:\n    print(\"No se pudo convertir\")\n",
    "expected_output": "No se pudo convertir",
    "explicacion": "int(\"abc\") lanza ValueError, no TypeError. Al capturar la excepción correcta, el bloque except responde y el programa no se detiene.",
    "conceptos": ["try/except captura errores en tiempo de ejecución.", "Cada tipo de error tiene su clase: TypeError, ValueError…", "Leer el mensaje de error dice qué excepción lanzar."],
    "pistas": ["Ejecuta el código: el error dice 'ValueError' o 'TypeError'?", "El texto \"abc\" no es un número: la clase está en el mensaje."],
    "keywords": ["try", "except", "int", "print"]
  },
  {
    "id_nivel": "mision_21",
    "title": "Números Precisos",
    "dificultad": "Avanzado",
    "modalidad": "Terminal",
    "briefing_mision": "El observatorio pide cálculos con precisión matemática. Importa el módulo de matemáticas y obtén la raíz cuadrada de 144, el redondeo hacia abajo de 3.7 y el área de un círculo de radio 2 con dos decimales.",
    "init_code": "# Importa el módulo math\n",
    "solution_code": "import math\n\nprint(math.sqrt(144))\nprint(math.floor(3.7))\narea = math.pi * 2 ** 2\nprint(round(area, 2))\n",
    "expected_output": "12.0\n3\n12.57",
    "conceptos": ["import math habilita funciones matemáticas.", "math.sqrt, math.floor, math.pi.", "round(numero, decimales) redondea."],
    "pistas": ["Todas las funciones del módulo se llaman con math.nombre().", "2 ** 2 es 2 al cuadrado."],
    "keywords": ["import", "math", "round", "print"]
  },
  {
    "id_nivel": "mision_22",
    "title": "Números en Cascada",
    "dificultad": "Avanzado",
    "modalidad": "Terminal",
    "briefing_mision": "Los factoriales siempre se calculan igual: multiplicando desde el número hasta 1. Implementa la versión recursiva de ese cálculo y muestra los factoriales del 1 al 5.",
    "init_code": "# Define factorial con recursión\n",
    "solution_code": "def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\n\nfor i in range(1, 6):\n    print(f\"{i}! = {factorial(i)}\")\n",
    "expected_output": "1! = 1\n2! = 2\n3! = 6\n4! = 24\n5! = 120",
    "conceptos": ["La recursión es una función que se llama a sí misma.", "Todo caso recursivo necesita un caso base que detenga.", "factorial(n) = n * factorial(n-1)."],
    "pistas": ["El caso base es n <= 1.", "El paso recursivo multiplica n por factorial(n-1)."],
    "keywords": ["def", "return", "for", "range", "print"]
  },
  {
    "id_nivel": "mision_23",
    "title": "Mascota de la Base",
    "dificultad": "Avanzado",
    "modalidad": "Terminal",
    "briefing_mision": "La base adoptó un perro robot. Define su plantilla con nombre y un método de saludo, crea una mascota llamada Rexi y haz que presente su ladrido.",
    "init_code": "# Define la clase Perro\n",
    "solution_code": "class Perro:\n    def __init__(self, nombre):\n        self.nombre = nombre\n\n    def ladrar(self):\n        return f\"{self.nombre} hace guau!\"\n\nrexi = Perro(\"Rexi\")\nprint(rexi.ladrar())\n",
    "expected_output": "Rexi hace guau!",
    "conceptos": ["class define una plantilla de objetos.", "__init__ inicializa cada instancia.", "self guarda los datos del objeto."],
    "pistas": ["El método especial __init__ recibe self y el nombre.", "Al crear el objeto: Perro(\"Rexi\")."],
    "keywords": ["class", "def", "print"]
  },
  {
    "id_nivel": "mision_24",
    "title": "Orden con Criterio",
    "dificultad": "Avanzado",
    "modalidad": "Terminal",
    "briefing_mision": "Un mapa registra puntos con dos coordenadas. Ordénalos primero por la primera coordenada y luego por la segunda, usando una función anónima como criterio.",
    "init_code": "puntos = [(3, 1), (1, 5), (2, 3)]\n# Ordena por cada coordenada\n",
    "solution_code": "puntos = [(3, 1), (1, 5), (2, 3)]\nordenados = sorted(puntos, key=lambda p: p[0])\nprint(ordenados)\npor_segundo = sorted(puntos, key=lambda p: p[1])\nprint(por_segundo)\n",
    "expected_output": "[(1, 5), (2, 3), (3, 1)]\n[(3, 1), (2, 3), (1, 5)]",
    "conceptos": ["lambda crea una función anónima de una línea.", "sorted(iterable, key=func) ordena con criterio.", "p[0] y p[1] acceden a cada coordenada."],
    "pistas": ["key=lambda p: p[0] ordena por la primera coordenada.", "El segundo orden usa p[1]."],
    "keywords": ["sorted", "lambda", "print"]
  },
  {
    "id_nivel": "mision_25",
    "title": "Generador Furtivo",
    "dificultad": "Avanzado",
    "modalidad": "Auditoría",
    "briefing_mision": "Un generador debe producir los números pares bajo demanda, uno a uno, según se le piden. Pero entrega solo el primero y el bucle exterior se detiene. Localiza la instrucción que corta la producción.",
    "init_code": "",
    "audit_tokens": [
      "def primeros_pares(limite):",
      "    for n in range(0, limite, 2):",
      "        return n",
      "",
      "for valor in primeros_pares(8):",
      "    print(valor)"
    ],
    "token_error_index": 2,
    "solution_code": "def primeros_pares(limite):\n    for n in range(0, limite, 2):\n        yield n\n\nfor valor in primeros_pares(8):\n    print(valor)\n",
    "expected_output": "0\n2\n4\n6",
    "explicacion": "return termina la función en la primera iteración y entrega un solo valor. yield la convierte en generador: produce cada pares cuando el bucle exterior lo pide.",
    "conceptos": ["yield convierte una función en generador.", "Un generador produce valores bajo demanda.", "return termina la función al instante."],
    "pistas": ["La instrucción entrega un valor y termina todo.", "La clave del generador es una palabra que se escribe igual que 'ceder'."],
    "keywords": ["for", "range", "yield", "print"]
  },
  {
    "id_nivel": "mision_26",
    "title": "Limpieza del Informe",
    "dificultad": "Experto",
    "modalidad": "Terminal",
    "briefing_mision": "Un informe llega con espacios de más y formato inconsistente. Límpialo, sepáralo en palabras, únelas con separador, muéstralo en mayúsculas y reemplaza una palabra clave.",
    "init_code": "texto = \"  hola mundo hoy es un gran día  \"\n# Limpia y transforma\n",
    "solution_code": "texto = \"  hola mundo hoy es un gran día  \"\nlimpio = texto.strip()\npalabras = limpio.split()\nprint(palabras)\nunido = \" | \".join(palabras)\nprint(unido)\nprint(unido.upper())\nprint(unido.replace(\"mundo\", \"PYTHON\"))\n",
    "expected_output": "['hola', 'mundo', 'hoy', 'es', 'un', 'gran', 'día']\nhola | mundo | hoy | es | un | gran | día\nHOLA | MUNDO | HOY | ES | UN | GRAN | DÍA\nhola | PYTHON | hoy | es | un | gran | día",
    "conceptos": ["strip() quita espacios de los extremos.", "split() separa en palabras.", "join(), upper() y replace() transforman texto."],
    "pistas": ["split() sin argumentos separa por espacios.", "join pone el separador entre cada palabra."],
    "keywords": ["strip", "split", "join", "upper", "replace", "print"]
  },
  {
    "id_nivel": "mision_27",
    "title": "Protocolo JSON",
    "dificultad": "Experto",
    "modalidad": "Terminal",
    "briefing_mision": "Una nave envía su configuración en formato JSON. Paréalo a un diccionario, sube el volumen, consulta el tema y muestra el estado actualizado.",
    "init_code": "import json\n\nconfig = json.loads('{\"tema\": \"oscuro\", \"volumen\": 8}')\n# Actualiza y consulta\n",
    "solution_code": "import json\n\nconfig = json.loads('{\"tema\": \"oscuro\", \"volumen\": 8}')\nconfig[\"volumen\"] = 10\nprint(config[\"tema\"])\nprint(config.get(\"volumen\"))\nprint(config)\n",
    "expected_output": "oscuro\n10\n{'tema': 'oscuro', 'volumen': 10}",
    "conceptos": ["json.loads() convierte texto JSON a Python.", "Un dict se actualiza asignando a su clave.", "La salida de un dict muestra las comillas simples."],
    "pistas": ["El tema es la clave \"tema\" del diccionario.", "Modifica config[\"volumen\"] y luego imprime."],
    "keywords": ["import", "json", "get", "print"]
  },
  {
    "id_nivel": "mision_28",
    "title": "El Clásico FizzBuzz",
    "dificultad": "Experto",
    "modalidad": "Ensamblaje",
    "briefing_mision": "Seguimiento requinta la prueba para reclutas: para cada número del 1 al 15, muestra Fizz si es múltiplo de 3, Buzz si es de 5, FizzBuzz si es de ambos, y el propio número en cualquier otro caso. Ensambla la lógica.",
    "init_code": "",
    "dnd_blocks": [
      "for i in range(1, 16):",
      "    if i % 15 == 0:",
      "        print(\"FizzBuzz\")",
      "    elif i % 3 == 0:",
      "        print(\"Fizz\")",
      "    elif i % 5 == 0:",
      "        print(\"Buzz\")",
      "    else:",
      "        print(i)"
    ],
    "solution_code": "for i in range(1, 16):\n    if i % 15 == 0:\n        print(\"FizzBuzz\")\n    elif i % 3 == 0:\n        print(\"Fizz\")\n    elif i % 5 == 0:\n        print(\"Buzz\")\n    else:\n        print(i)\n",
    "expected_output": "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz",
    "conceptos": ["Múltiplo de 3 y 5 a la vez: i % 15 == 0.", "elif encadena las condiciones.", "El orden de los if/elif importa."],
    "pistas": ["Revisa primero el caso de ambos múltiplos.", "El último bloque else imprime el número."],
    "keywords": ["for", "range", "if", "elif", "else", "print"]
  },
  {
    "id_nivel": "mision_29",
    "title": "Jefe Final: Reporte Académico",
    "dificultad": "Experto",
    "modalidad": "Terminal",
    "briefing_mision": "La academia evaluó a tres reclutas. Tu misión final integra lo aprendido: recorre el registro, calcula el promedio de cada uno, decide si aprobó o reprobó y emite un reporte por línea.",
    "init_code": "alumnos = [\n    {\"nombre\": \"Ana\", \"notas\": [8, 9, 7]},\n    {\"nombre\": \"Luis\", \"notas\": [6, 5, 7]},\n    {\"nombre\": \"Eva\", \"notas\": [10, 9, 9]}\n]\n# Calcula y reporta\n",
    "solution_code": "alumnos = [\n    {\"nombre\": \"Ana\", \"notas\": [8, 9, 7]},\n    {\"nombre\": \"Luis\", \"notas\": [6, 5, 7]},\n    {\"nombre\": \"Eva\", \"notas\": [10, 9, 9]}\n]\n\nfor alumno in alumnos:\n    promedio = sum(alumno[\"notas\"]) / len(alumno[\"notas\"])\n    estado = \"Aprobó\" if promedio >= 6 else \"Reprobó\"\n    print(f\"{alumno['nombre']}: {promedio:.1f} - {estado}\")\n",
    "expected_output": "Ana: 8.0 - Aprobó\nLuis: 6.0 - Aprobó\nEva: 9.3 - Aprobó",
    "conceptos": ["sum() y len() combinan para promediar.", "El condicional ternario decide en una línea.", "{promedio:.1f} formatea con un decimal."],
    "pistas": ["promedio = sum(...) / len(...).", "El formato .1f redondea a un decimal."],
    "keywords": ["for", "sum", "len", "if", "print"]
  },
  {
    "id_nivel": "mision_30",
    "title": "Jefe Final: Búsqueda Lineal",
    "dificultad": "Experto",
    "modalidad": "Terminal",
    "briefing_mision": "Un registro de códigos puede contener el objetivo o no. Implementa la búsqueda que recorra uno a uno los elementos, reporte la posición si lo encuentra o avise si no existe.",
    "init_code": "datos = [45, 12, 78, 23, 89, 34]\nbuscar = 23\n# Implementa la búsqueda\n",
    "solution_code": "datos = [45, 12, 78, 23, 89, 34]\nbuscar = 23\n\nencontrado = False\nfor i, valor in enumerate(datos):\n    if valor == buscar:\n        print(f\"Encontrado en posición {i}\")\n        encontrado = True\n        break\n\nif not encontrado:\n    print(\"No encontrado\")\n",
    "expected_output": "Encontrado en posición 3",
    "conceptos": ["enumerate() da (índice, valor).", "break detiene la búsqueda al encontrar.", "Una bandera (encontrado) controla el final."],
    "pistas": ["Usa enumerate(datos) para tener el índice.", "break tras encontrar ahorra vueltas."],
    "keywords": ["for", "enumerate", "if", "break", "print"]
  },
  {
    "id_nivel": "mision_31",
    "title": "Código Infraestructural",
    "dificultad": "Experto",
    "modalidad": "Auditoría",
    "briefing_mision": "El criptógrafo extrae los emails de un texto, pero el patrón que usa recorta los dominios. Encuentra la línea con el error y corrige mentalmente cuál sería el patrón adecuado.",
    "init_code": "",
    "audit_tokens": [
      "import re",
      "",
      "texto = \"Contacto: ana@correo.com o llamar al 555-0147\"",
      "emails = re.findall(r\"[a-z]+@[a-z]+\", texto)",
      "print(emails)"
    ],
    "token_error_index": 3,
    "solution_code": "import re\n\ntexto = \"Contacto: ana@correo.com o llamar al 555-0147\"\nemails = re.findall(r\"[\\w.]+@[\\w.]+\", texto)\nprint(emails)\n",
    "expected_output": "['ana@correo.com']",
    "explicacion": "El patrón [a-z]+@[a-z]+ solo acepta letras, por eso recorta \".com\". El patrón correcto incluye punto: [\\w.]+@[\\w.]+, capturando el dominio completo.",
    "conceptos": ["re.findall(patrón, texto) extrae coincidencias.", "[\\w.] acepta letras, dígitos, _ y punto.", "Un patrón demasiado corto recorta resultados."],
    "pistas": ["¿Qué parte del email se pierde al imprimir?", "El dominio incluye un punto que el patrón no admite."],
    "keywords": ["import", "re", "findall", "print"]
  },
  {
    "id_nivel": "mision_32",
    "title": "Jefe Final: El Decorador",
    "dificultad": "Experto",
    "modalidad": "Ensamblaje",
    "briefing_mision": "El último desafío: envuelve un saludo para que, al invocarlo, se anuncien el inicio y el fin automáticamente. Ensambla la función que envuelve, el decorador y la función decorada.",
    "init_code": "",
    "dnd_blocks": [
      "def envolver(func):",
      "    def decorada():",
      "        print(\"--- Inicio ---\")",
      "        func()",
      "        print(\"--- Fin ---\")",
      "    return decorada",
      "@envolver",
      "def saludo():",
      "    print(\"¡Hola, Python!\")",
      "saludo()"
    ],
    "solution_code": "def envolver(func):\n    def decorada():\n        print(\"--- Inicio ---\")\n        func()\n        print(\"--- Fin ---\")\n    return decorada\n\n@envolver\ndef saludo():\n    print(\"¡Hola, Python!\")\n\nsaludo()\n",
    "expected_output": "--- Inicio ---\n¡Hola, Python!\n--- Fin ---",
    "explicacion": "El decorador @envolver sustituye saludo por decorada. Al llamar saludo() se ejecuta el envoltorio: imprime Inicio, llama a la función original y cierra con Fin.",
    "conceptos": ["@decorador envuelve la función siguiente.", "decorada() añade comportamiento antes y después.", "return decorada devuelve la función nueva."],
    "pistas": ["La función interna (decorada) llama a func() entre los dos mensajes.", "El símbolo @ se coloca justo antes de def saludo."],
    "keywords": ["def", "return", "print"]
  }
];

export function getLevelByIndex(index) {
    return LEVELS[index] || null;
}

export function getLevelById(id) {
    return LEVELS.find((l) => l.id_nivel === id) || null;
}

export function getLevelIndex(id) {
    return LEVELS.findIndex((l) => l.id_nivel === id);
}